# Generated by Django 5.1.6 on 2025-03-10 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionGroupAssigment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("MANAGER", "Managers"),
                            ("CUSTOMER", "Customer"),
                            ("ADMINISTRATOR", "Administrator"),
                            ("EDITOR", "Content Editor"),
                        ],
                        default="CUSTOMER",
                        max_length=25,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Group Assignment",
                "verbose_name_plural": "User Group Assignments",
            },
        ),
    ]
