# Generated by Django 5.1.6 on 2025-03-12 19:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_permissiongroupassigment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=20)),
                ("street", models.CharField(max_length=50)),
                ("apartment_number", models.CharField(blank=True, max_length=10)),
                ("house_number", models.CharField(blank=True, max_length=6)),
                (
                    "mobile_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
            ],
        ),
    ]
