# Generated by Django 5.1.6 on 2025-03-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PermissionGroupAssigment",
        ),
    ]
