version: '3.8'
services:

  consul:
    image: hashicorp/consul:latest
    container_name: consul1
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data  # dodaj persistence
    networks:
      - microservices-network

  gateway-app:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8010:8010"
    environment:
      - DATABASE_URL=postgresql://gateway_user:gateway_pass@gateway-db:5432/gateway_db
      - REDIS_URL=redis://gateway-redis:6379
      - RABBITMQ_URL=amqp://gateway_user:gateway_pass@gateway-rabbitmq:5672
      - ALLOWED_HOST=localhost:3001
      - ALLOWED_ORIGIN=xyz.com
      - ALLOWED_ORIGIN_HOST=http://xyz.com
    depends_on:
      - gateway-db
      - gateway-redis
      - gateway-rabbitmq
      - consul
    networks:
      - gateway-network
      - microservices-network

  gateway-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=gateway_db
      - POSTGRES_USER=gateway_user
      - POSTGRES_PASSWORD=gateway_pass
    ports:
      - "5442:5432"  # Twój niestandardowy port (5432 + 10)
    volumes:
      - gateway_postgres_data:/var/lib/postgresql/data
    networks:
      - gateway-network

  gateway-redis:
    image: redis:7-alpine
    ports:
      - "6389:6379"  # Twój niestandardowy port (6379 + 10)
    volumes:
      - gateway_redis_data:/data
    networks:
      - gateway-network

  gateway-rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=gateway_user
      - RABBITMQ_DEFAULT_PASS=gateway_pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - gateway_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gateway-network
      - microservices-network

  gateway-celery-worker:
    build:
      context: ..
      dockerfile: gateway/DockerfileCelery
    container_name: gateway-celery-worker
    command: celery -A celery_worker worker --loglevel=INFO -P gevent -Q auth_queue
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/app/celery_worker
      - DATABASE_URL=postgresql://gateway_user:gateway_pass@gateway-db:5432/gateway_db
      - REDIS_URL=redis://gateway-redis:6379
      - RABBITMQ_URL=amqp://gateway_user:gateway_pass@gateway-rabbitmq:5672
      - CELERY_BROKER_URL=amqp://gateway_user:gateway_pass@gateway-rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://gateway-redis:6379/0
    depends_on:
      - gateway-db
      - gateway-redis
      - gateway-rabbitmq
    networks:
      - gateway-network
      - microservices-network
    restart: unless-stopped

volumes:
  gateway_postgres_data:
  gateway_redis_data:
  gateway_rabbitmq_data:
  consul_data:  # dodaj volume dla consul

networks:
  gateway-network:
    driver: bridge
  microservices-network:
    external: true
