# Generated by Django 5.1.6 on 2025-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissiongroupassigment",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("MANAGER", "Managers"),
                    ("CUSTOMER_SERVICE", "Customer Service"),
                    ("CONTENT_EDITOR", "Content Editor"),
                    ("CUSTOMER", "Customer"),
                    ("ANONYMOUS", "Anonymous user"),
                ],
                default="CUSTOMER",
                max_length=25,
            ),
        ),
    ]
