version: '3.8'

services:
  product-service:
    build:
      context: ..
      dockerfile: products/Dockerfile
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"  # Mapuje port 8000 kontenera na 8002 hosta
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - PRODUCT_DB_NAME=product_service
      - DB_HOST=product-db
      - DB_PORT=5432
      - REDIS_HOST=product-redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=product-rabbitmq
      - RABBITMQ_PORT=5673
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    depends_on:
      - product-db
      - product-redis
    networks:
      - product-network
      - microservices-network

  product-db:
    image: postgres:15
    volumes:
      - product_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product_service
    ports:
      - "5435:5432"  # Mapuje port 5432 kontenera na 5433 hosta
    networks:
      - product-network

  product-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  # Twój niestandardowy port (6379 + 10)
    volumes:
      - product_redis_data:/data
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
  microservices-network:
    external: true  # Używa istniejącej sieci głównego projektu
    # Uwaga: Musisz najpierw utworzyć tę sieć używając: docker network create main-network

volumes:
  product_db_data:
  product_redis_data: