
# docker-compose.yml
version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: authenticate/Dockerfile
    container_name: auth-service1
    command: >
      bash -c " 
      python manage.py makemigrations && 
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8100"
    ports:
      - "8100:8100"
    environment:
      - POSTGRES_DB=authdb1
      - POSTGRES_USER=authadmin
      - POSTGRES_PASSWORD=authpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - auth-network
      - microservices-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGUSER=authadmin
      - POSTGRES_DB=authdb1
      - POSTGRES_USER=authadmin
      - POSTGRES_PASSWORD=authpassword
    ports:
      - "5432:5432"
    networks:
      - auth-network
    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: auth-redis1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # Enable persistence
    networks:
      - auth-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  auth-network:
    driver: bridge
  microservices-network:
    external: true

