# Generated by Django 5.2.1 on 2025-05-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_cart_cartelement"),
        ("orders", "0002_orderitem_product_orderevent"),
    ]

    operations = []
