# Generated by Django 5.2.1 on 2025-05-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_merge_20250508_1958"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartelement",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartelement",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartElement",
        ),
    ]
