# Generated by Django 5.1.6 on 2025-02-16 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("low_stock_treshold", models.PositiveIntegerField(default=5)),
                ("reserved_quantity", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sunlight",
                    models.CharField(
                        choices=[
                            ("full", "Full Sun"),
                            ("partial", "Partial Sun"),
                            ("shade", "Shade"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "water_needs",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "care_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, help_text="Height in cm", max_digits=5
                    ),
                ),
                (
                    "spread",
                    models.DecimalField(
                        decimal_places=2, help_text="Spread in cm", max_digits=5
                    ),
                ),
                ("bloom_time", models.CharField(blank=True, max_length=50)),
                ("flower_color", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="flowers/"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flower",
                "verbose_name_plural": "Flowers",
                "ordering": ["name"],
            },
        ),
    ]
