# Generated by Django 5.1.7 on 2025-03-20 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Event ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploaded", "Uploaded"),
                            ("blocked", "Blocked"),
                            ("blocked_reservations", "Blocked Reservations"),
                            ("reserved", "Reserved"),
                            ("subtracted", "Subtracted"),
                        ],
                        default="created",
                        max_length=25,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantity affected by this event",
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Inventory Event",
                "verbose_name_plural": "Inventory Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservedInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Reservation ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reserved Quantity"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Optional reference (order ID, cart ID, etc.)",
                        max_length=255,
                        null=True,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Reserved Inventory",
                "verbose_name_plural": "Reserved Inventories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventories",
            },
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="low_stock_treshold",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="product_id",
        ),
        migrations.AddField(
            model_name="inventory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Low Stock Threshold"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Inventory ID",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Total Quantity"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="reserved_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Reserved Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="care_difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sunlight",
            field=models.CharField(
                choices=[
                    ("full", "Full Sun"),
                    ("partial", "Partial Sun"),
                    ("shade", "Shade"),
                ],
                default="partial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="water_needs",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["product"], name="products_in_product_068dc9_idx"
            ),
        ),
        migrations.AddField(
            model_name="inventoryevent",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="products.inventory",
                verbose_name="Inventory",
            ),
        ),
        migrations.AddField(
            model_name="inventoryevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="reservedinventory",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="products.inventory",
                verbose_name="Inventory",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryevent",
            index=models.Index(
                fields=["inventory"], name="products_in_invento_60cb23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryevent",
            index=models.Index(fields=["event"], name="products_in_event_736e44_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryevent",
            index=models.Index(
                fields=["created_at"], name="products_in_created_4f9e44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservedinventory",
            index=models.Index(
                fields=["inventory"], name="products_re_invento_a0616e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservedinventory",
            index=models.Index(
                fields=["created_at"], name="products_re_created_82496d_idx"
            ),
        ),
    ]
